name: master

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: jbdelavoix/ubuntu-python-terraform-ansible-hvault

jobs:
  build:
    environment: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -f Dockerfile -t ${{ env.IMAGE_NAME }}:$(git rev-parse --short HEAD) -t ${{ env.IMAGE_NAME }}:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker image
        run: docker push --all-tags ${{ env.IMAGE_NAME }}
